name: Check JSON-LD Graph

on:
  workflow_run:
      workflows: ['Deploy static content to Pages']
      types: [completed]
      branches:
          - 'beta'

jobs:
  update-jsonld:
    runs-on: ubuntu-latest  # Specify the machine type
      
    steps:
    
    # - name: Checkout Code
    #   uses: actions/checkout@v4
    #   with:
    #     fetch-depth: 0

    - name: Ensure the JSON-LD files are functional
      id: check-graph
      uses: WCRP-CMIP/CMIP-LD/actions/check-graph@main


